### ISSUE TITLE
A4988 and DRV8255 driver mode pins

### ISSUE THREAD

**Issue by rdagger** [alangibson/steppyr#2]
In a4988.py (lines 34-36) **.self** is missing in front of ms#_pin.
Also there is  no logic to handle the default values for ms1_pin, ms2_pin & ms3_pin.  Default values of None cause the activate method to fail.

**Comment by simonbuehler** [comment]
@rdagger thanks for the fix, now it works but only once, i gues sth isnt released :

`4988.py:36: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings`

any idea whats wrong?

**Comment by rdagger** [comment]
When your program exits use the GPIO.cleanup() function to release the channels and return them to their default state. This step is crucial to prevent conflicts when reusing GPIO channels in different scripts or when you later rerun your program.

Check if any other processes or components are using the GPIO channel you intend to use.

**Comment by simonbuehler** [comment]
thanks for your feedback, I got it working this way after some fiddling:

```python
import sys
sys.path.insert(0, '/home/pi/steppyr/src')
from steppyr.profiles import accel
from steppyr import StepperController
from steppyr.drivers.drv8825 import DRV8825Driver
import RPi.GPIO as GPIO
import asyncio

# Pins are adapted to the Waveshare Stepper Motor HAT
dir_pin = 13
step_pin = 19
enable_pin = 12
ms1_pin = 16
ms2_pin = 17
ms3_pin = 20


controller = StepperController( 
	profile=accel.AccelProfile(),
	driver=DRV8825Driver( 
    dir_pin=dir_pin, 
    step_pin=step_pin, 
    enable_pin=enable_pin, 
    ms1_pin=ms1_pin, 
    ms2_pin=ms2_pin, 
    ms3_pin=ms3_pin
	)
)
controller.activate()
controller.set_microsteps(8)
motorA_steps_per_rev = 200

#actually no idea how to get max speed without trial and error
motorA_max_rpm = 300 


# steps per second
controller.set_target_speed(motorA_steps_per_rev * ( motorA_max_rpm / 60 ) )
controller.set_target_acceleration(500)

# Perform movement here

async def run():
	controller.rotate(720)
	await controller.run_until_done()
	controller.move(-200 * 8)
	await controller.run_until_done()
            


loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(run())
finally:
	controller.shutdown()
	loop.close()
	GPIO.cleanup()
```

**Comment by simonbuehler** [comment]
https://github.com/alangibson/steppyr/blob/25c06e1f1b73c305672962dd91d3653e8c7bf05c/src/steppyr/drivers/a4988.py#L34

ist still missing the .self

**Comment by simonbuehler** [comment]
@alangibson hey, you think you could fix this and push it to pypi?
